<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class LocationSeeder extends Seeder
{
    public function run(): void
    {
        $locations = [

            /* ============================ TIER 1 — primary money cities ============================ */
            [
                'name' => 'Erode',
                'short_name' => 'Erode',
                'state' => 'Tamil Nadu',
                'district' => 'Erode',
                'latitude' => 11.3410,
                'longitude' => 77.7172,
                'priority_tier' => 1,
                'sort_order' => 1,
                'image' => 'images/whyy.webp',
                'excerpt' => 'Next Level Packers and Movers is a local packers and movers company in Erode, providing house shifting, office relocation, packing and storage since 2015.',
                'meta_title' => 'Packers and Movers in Erode | House Shifting, Office Relocation & Storage',
                'meta_description' => 'Looking for packers and movers in Erode? Next Level offers house shifting, office moving, packing, loading and storage from Chithode. Call +91 93635 55311 for a free quote.',
                'description' => "Erode is where Next Level Packers and Movers began, and it remains the base our crews work from. Our office sits on Sakthi Main Road at Nadapalayam, Chithode, which means most Erode moves are handled by people who already know the city — the lift widths in older apartments on Bypass Road, the narrow gulleys behind Perumapalayam, the way Perundurai Road traffic builds up from 5 PM.\n\nWe move households and offices across every part of the district, not just the town. That includes Perundurai, Bhavani, Gobichettipalayam, Sathyamangalam, Anthiyur, Veppadai, Modakkurichi, Mettupalayam and the smaller villages between them. Because our vehicles are based here rather than being dispatched from Chennai or Coimbatore, we can usually quote same-day and arrive the same day for local Erode shifts.\n\nThe textile and hosiery trade drives a large share of Erode's moving demand. We have moved a lot of shop, showroom, godown and office stock for businesses around Kumaran Road, Palayamkottai, the textile market and the Erode–Karur and Erode–Coimbatore industrial belts, and we are set up to handle bulk, palletised and repetitive scheduled movements as well as ordinary household moves.\n\nOur storage facility in Erode covers the gap between the two most common local needs: a house move that runs ahead of the possession date on the new flat, and a business that needs stock held between two premises.",
                'localities' => ['Erode Junction', 'Chithode', 'Nadapalayam', 'Perundurai Road', 'Bypass Road', 'Kongu Kalam', 'Sathyamangalam Road', 'Mettupalayam', 'Palayamkottai', 'Elumalam', 'Periyar Nagar', 'Kavithai', 'Vaidyanathapuram', 'Modakkurichi', 'Gobichettipalayam Road', 'Udayamperur'],
                'popular_routes' => ['Erode to Coimbatore', 'Erode to Tiruppur', 'Erode to Chennai', 'Erode to Bengaluru', 'Erode to Salem', 'Erode to Tiruchy'],
            ],
            [
                'name' => 'Tiruppur',
                'short_name' => 'Tiruppur',
                'state' => 'Tamil Nadu',
                'district' => 'Tiruppur',
                'latitude' => 11.1085,
                'longitude' => 77.3411,
                'priority_tier' => 1,
                'sort_order' => 2,
                'image' => 'images/s8.webp',
                'excerpt' => 'Packers and movers in Tiruppur for house shifting, factory and office relocation, packing, loading and transport. Local team, same-day service.',
                'meta_title' => 'Packers and Movers in Tiruppur | House, Office & Factory Shifting',
                'meta_description' => 'Next Level Packers and Movers in Tiruppur — house shifting, factory and office relocation, packing, loading and goods transport. Call +91 93635 55311 for a free quote.',
                'description' => "Tiruppur is India's knitwear capital and it moves constantly — people, machines, sample stock, finished goods and whole factories. We run a dedicated crew and vehicle allocation for Tiruppur, roughly 50 km from our Erode base, which is close enough that we are not reselling someone else's truck.\n\nResidential moves around Tiruppur usually cluster along Avinashi Road, Palladam Road, Mangalam Road, Kumaran Road, Gandhi Nagar, Ram Nagar and Puthur, plus the newer apartment layouts that have come up around Avinashi and Perumanallur. We handle all of them, and because we know which streets need a smaller vehicle and which can take a 32-footer, the quote we give you is the price you pay.\n\nThe commercial side is where Tiruppur really needs a mover who understands the job. We have moved knitting machines, dyeing units, steam presses, showroom inventories and full factory setups with line clearance. For businesses we plan the shutdown to the hour, and we sequence machines out first, stock second, so a factory can restart production at the new unit without losing a day of output.\n\nWe also run regular scheduled goods transport for Tiruppur businesses moving stock to Tiruppur knitwear exporters and to Bengaluru, Chennai and Hyderabad distribution points, with monthly rate cards and priority slots.",
                'localities' => ['Avinashi Road', 'Palladam Road', 'Mangalam Road', 'Kumaran Road', 'Puthur', 'Mattuthavani', 'Gandhi Nagar', 'Ram Nagar', 'Samuthamputhoor', 'Perumanallur', 'Vellakoil', 'Udumalaipettai', 'Anupparpalayam'],
                'popular_routes' => ['Tiruppur to Erode', 'Tiruppur to Coimbatore', 'Tiruppur to Chennai', 'Tiruppur to Bengaluru', 'Tiruppur to Salem', 'Tiruppur to Madurai'],
            ],
            [
                'name' => 'Coimbatore',
                'short_name' => 'Coimbatore',
                'state' => 'Tamil Nadu',
                'district' => 'Coimbatore',
                'latitude' => 11.0168,
                'longitude' => 76.9558,
                'priority_tier' => 1,
                'sort_order' => 3,
                'image' => 'images/why3.webp',
                'excerpt' => 'Packers and movers in Coimbatore for house shifting, office relocation, factory and institutional shifting, packing and storage.',
                'meta_title' => 'Packers and Movers in Coimbatore | House, Office & Factory Shifting',
                'meta_description' => 'Next Level Packers and Movers in Coimbatore — house shifting, office and factory relocation, packing, loading and storage. Call +91 93635 55311 for a free quote.',
                'description' => "Coimbatore is our biggest volume market and the one we plan hardest for. It is a 90-minute run from Erode on the NH-47, which is close enough for a same-day crew and a night return, and far enough that we keep a dedicated team rather than stretching Erode's.\n\nHouse shifting in Coimbatore concentrates in RS Puram, Gandhipuram, Singanalur, Ukkadam, Sukkamvaram, Saibaba Colony, Race Course, Peelamedu, Valangaiman Street, Trichy Main Road, Ganapathy and Selvapuram, and increasingly in the apartment clusters around Thudiyalur, Perumanallur and Vellakoil. Each of those has its own access quirks — the older RS Puram and Ukkadam streets will not take a 32-footer at all, while the Thudiyalur-side layouts usually will. We size the vehicle to the street before we quote, not after.\n\nCommercially, Coimbatore is a different conversation again. We shift engineering units, educational institutions, hospitals and clinics, IT and trading offices, showrooms and retail chains across Gandhipuram, Peelamedu, Singur, Ambalal Patil Road, Mettupalayam Road and the SIDCO industrial estate. Clinic and hospital moves are planned around clinical schedules; educational institution moves are planned around exam calendars and term dates.\n\nFor Coimbatore customers who need a gap between possession and move-in, or who are between premises, we use our Erode storage facility — which is honestly the more practical option than trying to fit goods into a Coimbatore godown at Coimbatore godown rates.",
                'localities' => ['R.S. Puram', 'Gandhipuram', 'Singanalur', 'Ukkadam', 'Sukkamvaram', 'Saibaba Colony', 'Race Course', 'Peelamedu', 'Singur', 'Valangaiman Street', 'Trichy Main Road', 'Avinashi Road', 'Mettupalayam Road', 'Ganapathy', 'Selvapuram', 'Thudiyalur'],
                'popular_routes' => ['Coimbatore to Erode', 'Coimbatore to Tiruppur', 'Coimbatore to Chennai', 'Coimbatore to Bengaluru', 'Coimbatore to Palakkad', 'Coimbatore to Salem'],
            ],

            /* ============================ TIER 2 — major regional cities ============================ */
            [
                'name' => 'Salem',
                'short_name' => 'Salem',
                'state' => 'Tamil Nadu',
                'district' => 'Salem',
                'latitude' => 11.6643,
                'longitude' => 78.1460,
                'priority_tier' => 2,
                'sort_order' => 4,
                'excerpt' => 'Packers and movers in Salem for house shifting, office relocation, textile and factory moving, packing and transport services.',
                'meta_title' => 'Packers and Movers in Salem | House Shifting & Office Relocation',
                'meta_description' => 'Next Level Packers and Movers in Salem — house shifting, office relocation, factory and textile unit shifting, packing and transport. Call +91 93635 55311.',
                'description' => "Salem has a long textile and steel history and a correspondingly large amount of industrial shifting, alongside a steady flow of household moves along the Salem–Namakkal and Salem–Coimbatore corridors.\n\nWe take household and office moves across Salem town, Hasthampatti, Attur, Salem North and South, Kondalampatti and the villages in between, and we run the industrial side for steel, textile, sari and garment units — where the work is as much about sequencing production shutdown as it is about moving steel.\n\nSalem moves are usually scheduled as a night outbound and day return where the distance allows, so a Salem household sees a single crew rather than a different one for loading and one for delivery.",
                'localities' => ['Salem Town', 'Hasthampatti', 'Attur', 'Kondalampatti', 'Salem North', 'Ammapet', 'Edapadi', 'Omalur', 'Neruppur', 'Kollam'],
                'popular_routes' => ['Salem to Chennai', 'Salem to Coimbatore', 'Salem to Erode', 'Salem to Namakkal', 'Salem to Bengaluru', 'Salem to Tiruppur'],
            ],
            [
                'name' => 'Tiruchirappalli',
                'short_name' => 'Tiruchy',
                'state' => 'Tamil Nadu',
                'district' => 'Tiruchirappalli',
                'latitude' => 10.7905,
                'longitude' => 78.7047,
                'priority_tier' => 2,
                'sort_order' => 5,
                'excerpt' => 'Packers and movers in Tiruchirappalli (Trichy) for house shifting, factory and office relocation, packing, loading and transport.',
                'meta_title' => 'Packers and Movers in Trichy | House Shifting & Factory Relocation',
                'meta_description' => 'Next Level Packers and Movers in Tiruchirappalli — house shifting, office and factory relocation, packing, loading and transport. Call +91 93635 55311.',
                'description' => "Trichy is a long-haul run from our Erode base, so we plan it as an overnight or same-day-long-distance job with a dedicated vehicle rather than trying to do it as a day trip.\n\nWe cover house shifting and office relocation across Srirangam, Woraiyur, K.K. Nagar, Thillai Nagar, Golden Rock, Chathirampatti and the newer layouts towards Puthanatham, plus industrial and institutional shifting for the engineering units around Gugalpuram and the transport corridor businesses along the Madurai and Thanjavur routes.\n\nBecause the distance from Erode to Trichy is real, we are explicit about the plan before booking: vehicle type, start time, expected delivery window, and who to call on the road. No surprises at the destination.",
                'localities' => ['Srirangam', 'Woraiyur', 'K.K. Nagar', 'Thillai Nagar', 'Golden Rock', 'Chathirampatti', 'K.K. Pudur', 'Thiruverumbur', 'Manachanallur', 'Puthanatham'],
                'popular_routes' => ['Trichy to Chennai', 'Trichy to Madurai', 'Trichy to Coimbatore', 'Trichy to Erode', 'Trichy to Tiruppur', 'Trichy to Salem'],
            ],
            [
                'name' => 'Namakkal',
                'short_name' => 'Namakkal',
                'state' => 'Tamil Nadu',
                'district' => 'Namakkal',
                'latitude' => 11.2189,
                'longitude' => 78.1677,
                'priority_tier' => 2,
                'sort_order' => 6,
                'excerpt' => 'Packers and movers in Namakkal for house shifting, transport, packing and industrial equipment relocation across Namakkal district.',
                'meta_title' => 'Packers and Movers in Namakkal | House Shifting & Transport Service',
                'meta_description' => 'Next Level Packers and Movers in Namakkal — house shifting, packing, loading and goods transport across Namakkal district. Call +91 93635 55311 for a free quote.',
                'description' => "Namakkal sits between our two busiest corridors, Erode to Salem and Erode to Tiruppur, which makes it a straightforward and reliable destination for us.\n\nWe handle house shifting, office moves and transport across Namakkal town, Rasipuram, Paramathi Velur, Mohanur, Sendamangalam, Namakkal and Pallipalayam, together with the wool and textile units that operate in this district. Machinery and equipment relocation for the woollen industry is routine work for us, and we handle it with the same care we give a household fridge.\n\nFor Namakkal customers, a phone call in the morning very often means the same-day crew, because we are already on the road between these cities.",
                'localities' => ['Namakkal Town', 'Rasipuram', 'Paramathi Velur', 'Mohanur', 'Sendamangalam', 'Pallipalayam', 'Kabilimalai', 'Kunnathur', 'Mangalam'],
                'popular_routes' => ['Namakkal to Erode', 'Namakkal to Salem', 'Namakkal to Coimbatore', 'Namakkal to Tiruppur', 'Namakkal to Chennai', 'Namakkal to Karur'],
            ],
            [
                'name' => 'Karur',
                'short_name' => 'Karur',
                'state' => 'Tamil Nadu',
                'district' => 'Karur',
                'latitude' => 10.9601,
                'longitude' => 78.0766,
                'priority_tier' => 2,
                'sort_order' => 7,
                'excerpt' => 'Packers and movers in Karur for house shifting, textile unit relocation, packing, loading and transport services.',
                'meta_title' => 'Packers and Movers in Karur | House Shifting & Textile Unit Moving',
                'meta_description' => 'Next Level Packers and Movers in Karur — house shifting, textile unit relocation, packing, loading and transport. Call +91 93635 55311 for a free quote.',
                'description' => "Karur is a textile city — bed linen, terry towels and saris — and its moving market is correspondingly dominated by factory, godown and showroom relocation alongside ordinary household shifts.\n\nWe move household goods across Karur town, Kulanthai, Pasamarthi, Pallikonda, Mangalam, Aravakurichi and the outlying villages, and we handle the industrial side for spinning, weaving, dyeing and garment units including machinery, raw stock and finished goods. Textile machinery needs a different approach to a household sofa: it needs to be crated, lifted with proper equipment and reinstalled, and that is what we do.\n\nKarur is on our Erode route so we are frequently on the road to and from it, which means same-day and scheduled-contract moves are both easy to arrange.",
                'localities' => ['Karur Town', 'Kulanthai', 'Pasamarthi', 'Pallikonda', 'Mangalam', 'Aravakurichi', 'Chettinad', 'Pugalur', 'Krishnarayapuram'],
                'popular_routes' => ['Karur to Erode', 'Karur to Coimbatore', 'Karur to Tiruppur', 'Karur to Chennai', 'Karur to Namakkal', 'Karur to Trichy'],
            ],
            [
                'name' => 'Dharmapuri',
                'short_name' => 'Dharmapuri',
                'state' => 'Tamil Nadu',
                'district' => 'Dharmapuri',
                'latitude' => 12.1211,
                'longitude' => 78.1580,
                'priority_tier' => 2,
                'sort_order' => 8,
                'excerpt' => 'Packers and movers in Dharmapuri for house shifting, packing, loading and goods transport across Dharmapuri district.',
                'meta_title' => 'Packers and Movers in Dharmapuri | House Shifting & Packing Services',
                'meta_description' => 'Next Level Packers and Movers in Dharmapuri — house shifting, packing, loading and goods transport across Dharmapuri district. Call +91 93635 55311.',
                'description' => "Dharmapuri sits on the Bengaluru side of our Erode base, which makes it one of our cleaner long-haul destinations. We run regular scheduled moves to Dharmapuri, Harur, Palacode, Pennapuram and Karimangalam.\n\nHouse shifting and packing is the bulk of the work, along with transport for the agriculture and granite businesses around the district. We also take on Dharmapuri as a source for moves into Bengaluru, which is a direction we run every week.\n\nBengaluru-bound moves from Dharmapuri are usually scheduled as night outbound and morning delivery, so the household is not waiting around with boxes for a day.",
                'localities' => ['Dharmapuri Town', 'Harur', 'Palacode', 'Pennapuram', 'Karimangalam', 'Nallampalli', 'Bannari', 'Rasipuram Road'],
                'popular_routes' => ['Dharmapuri to Bengaluru', 'Dharmapuri to Erode', 'Dharmapuri to Salem', 'Dharmapuri to Chennai', 'Dharmapuri to Coimbatore', 'Dharmapuri to Hosur'],
            ],
            [
                'name' => 'Bengaluru',
                'short_name' => 'Bengaluru',
                'state' => 'Karnataka',
                'district' => 'Bengaluru Urban',
                'latitude' => 12.9716,
                'longitude' => 77.5946,
                'priority_tier' => 2,
                'sort_order' => 9,
                'excerpt' => 'Packers and movers in Bengaluru for house shifting from Tamil Nadu, office relocation, packing and two-wheeler shifting with door delivery.',
                'meta_title' => 'Packers and Movers in Bengaluru | House Shifting from Tamil Nadu',
                'meta_description' => 'Next Level Packers and Movers in Bengaluru — house shifting from Tamil Nadu, office relocation, packing, loading and two-wheeler shifting. Call +91 93635 55311.',
                'description' => "Bengaluru is our most requested out-of-state destination, and it is the direction most of our international-looking domestic moves actually take — people moving from Erode, Coimbatore and Tiruppur to jobs and colleges in the city.\n\nWe run dedicated Erode to Bengaluru routes rather than treating Bengaluru as a spot job. That means predictable vehicle availability, a known crew, and a delivery window we can commit to. Typical Erode–Bengaluru distance is around 340 km, so we typically load in the evening, drive overnight and deliver the next morning, which is what most customers prefer.\n\nIn Bengaluru we cover house shifting and office relocation across Whitefield, Electronic City, Marathahalli, HSR Layout, Jayanagar, Indiranagar, Koramangala, Hebbal, Yelahanka and Banashankari, along with packing, storage and two-wheeler shifting. Because the roads are harder than they are in Tamil Nadu, we plan the last-mile vehicle for the specific Bengaluru street rather than assuming a 32-footer will fit.",
                'localities' => ['Whitefield', 'Electronic City', 'Marathahalli', 'HSR Layout', 'Jayanagar', 'Indiranagar', 'Koramangala', 'Hebbal', 'Yelahanka', 'Banashankari', 'Yeshwanthpur', 'BTM Layout'],
                'popular_routes' => ['Bengaluru to Erode', 'Bengaluru to Coimbatore', 'Bengaluru to Tiruppur', 'Bengaluru to Chennai', 'Bengaluru to Salem', 'Bengaluru to Dharmapuri'],
            ],

            /* ============================ TIER 3 — district towns & localities ============================ */
            [
                'name' => 'Perundurai',
                'short_name' => 'Perundurai',
                'state' => 'Tamil Nadu',
                'district' => 'Erode',
                'latitude' => 11.2342,
                'longitude' => 77.6678,
                'priority_tier' => 3,
                'sort_order' => 10,
                'excerpt' => 'Packers and movers in Perundurai for local house shifting, office moving, packing and loading services in Erode district.',
                'meta_title' => 'Packers and Movers in Perundurai | House Shifting in Erode District',
                'meta_description' => 'Next Level Packers and Movers in Perundurai — local house shifting, office moving, packing and loading in Erode district. Call +91 93635 55311.',
                'description' => "Perundurai is a fast-growing industrial and residential town about 15 km from our Erode base, which means local Perundurai moves are effectively a same-day job for us.\n\nThe industrial estate here is a recurring source of work — machinery, raw materials, finished goods and factory setups all move in and out regularly — and alongside that we handle the residential side across the new apartment layouts and the older town streets.\n\nBecause Perundurai sits inside our home operating radius, we do not charge a distance premium. A Perundurai to Erode move is priced as a local move.",
                'localities' => ['Perundurai Town', 'Industrial Estate', 'Kunnathur Road', 'Sengappanayakkarpalayam', 'Bhadrakali Layout', 'Sivalayappanayakkarpalayam'],
                'popular_routes' => ['Perundurai to Erode', 'Perundurai to Coimbatore', 'Perundurai to Tiruppur', 'Perundurai to Bhavani', 'Perundurai to Namakkal'],
            ],
            [
                'name' => 'Bhavani',
                'short_name' => 'Bhavani',
                'state' => 'Tamil Nadu',
                'district' => 'Erode',
                'latitude' => 11.4425,
                'longitude' => 77.6181,
                'priority_tier' => 3,
                'sort_order' => 11,
                'excerpt' => 'Packers and movers in Bhavani for house shifting, packing, loading and goods transport across Bhavani and Erode district.',
                'meta_title' => 'Packers and Movers in Bhavani | House Shifting & Packing Services',
                'meta_description' => 'Next Level Packers and Movers in Bhavani — house shifting, packing, loading and goods transport in Bhavani, Erode district. Call +91 93635 55311.',
                'description' => "Bhavani is a textile town on the banks of the Cauvery, about 22 km north-west of Erode, and it falls comfortably inside our daily operating range.\n\nWe handle house shifting and packing across Bhavani town and the villages along the Erode–Bhavani road, alongside the textile units and machinery moves that this district's mills generate. A typical Bhavani job for us is a household shift or a mill's stock and equipment movement between premises.",
                'localities' => ['Bhavani Town', 'Koonam', 'Jambai', 'Puliyur', 'Bharani', 'Varapatti', 'Sengottai'],
                'popular_routes' => ['Bhavani to Erode', 'Bhavani to Sathyamangalam', 'Bhavani to Gobichettipalayam', 'Bhavani to Anthiyur', 'Bhavani to Tiruppur'],
            ],
            [
                'name' => 'Tiruchengode',
                'short_name' => 'Tiruchengode',
                'state' => 'Tamil Nadu',
                'district' => 'Erode',
                'latitude' => 11.3539,
                'longitude' => 77.7011,
                'priority_tier' => 3,
                'sort_order' => 12,
                'excerpt' => 'Packers and movers in Tiruchengode for house shifting, packing, loading and transport services in Erode district.',
                'meta_title' => 'Packers and Movers in Tiruchengode | House Shifting & Transport',
                'meta_description' => 'Next Level Packers and Movers in Tiruchengode — house shifting, packing, loading and transport in Erode district. Call +91 93635 55311 for a free quote.',
                'description' => "Tiruchengode sits just west of Erode town and is effectively within our same-day radius. It is one of the places where we most often do a combined move — a household shift here plus a delivery into Erode, or the reverse.\n\nHouse shifting, packing and loading in Tiruchengode are our regular work here, and we also handle the commercial and small industrial moves in and around the town. Being 5 km from our base means we can give a real same-day commitment rather than a vague next-day promise.",
                'localities' => ['Tiruchengode Town', 'Kailasamudi', 'Pudur', 'Sirunambundi', 'Kilpatti', 'Rudhramapalayam'],
                'popular_routes' => ['Tiruchengode to Erode', 'Tiruchengode to Coimbatore', 'Tiruchengode to Tiruppur', 'Tiruchengode to Gobichettipalayam'],
            ],
            [
                'name' => 'Sathyamangalam',
                'short_name' => 'Sathyamangalam',
                'state' => 'Tamil Nadu',
                'district' => 'Erode',
                'latitude' => 11.5045,
                'longitude' => 77.4551,
                'priority_tier' => 3,
                'sort_order' => 13,
                'excerpt' => 'Packers and movers in Sathyamangalam for house shifting, packing, loading and transport in Erode district.',
                'meta_title' => 'Packers and Movers in Sathyamangalam | House Shifting Services',
                'meta_description' => 'Next Level Packers and Movers in Sathyamangalam — house shifting, packing, loading and transport in Erode district. Call +91 93635 55311.',
                'description' => "Sathyamangalam is on the Erode–Coimbatore road at the foot of the hills, and it is a common stop for us because a lot of Coimbatore-bound movements pass through it.\n\nWe take house shifting, packing and loading jobs across Sathyamangalam and the surrounding villages, and we frequently combine a Sathyamangalam pickup with a Coimbatore or Erode delivery, which keeps the cost down for the customer rather than charging a full journey each way.\n\nThe town also has a cluster of educational institutions, so academic-season moves are noticeably busier here than in the rest of the year.",
                'localities' => ['Sathyamangalam Town', 'Guthi', 'Chinnar', 'Puthur', 'Boothampatti', 'Dhottapalayam'],
                'popular_routes' => ['Sathyamangalam to Erode', 'Sathyamangalam to Coimbatore', 'Sathyamangalam to Gobichettipalayam', 'Sathyamangalam to Tiruppur'],
            ],
            [
                'name' => 'Gobichettipalayam',
                'short_name' => 'Gobichettipalayam',
                'state' => 'Tamil Nadu',
                'district' => 'Erode',
                'latitude' => 11.4561,
                'longitude' => 77.4436,
                'priority_tier' => 3,
                'sort_order' => 14,
                'excerpt' => 'Packers and movers in Gobichettipalayam for house shifting, packing, loading and goods transport in Erode district.',
                'meta_title' => 'Packers and Movers in Gobichettipalayam | House Shifting & Transport',
                'meta_description' => 'Next Level Packers and Movers in Gobichettipalayam — house shifting, packing, loading and transport in Erode district. Call +91 93635 55311.',
                'description' => "Gobichettipalayam sits on the Sathyamangalam road and functions as a service hub for the western part of Erode district, so it gets a steady stream of both household and commercial moving work.\n\nWe handle house shifting, packing, loading and general goods transport across Gobichettipalayam, Settur, Gudumani, Kongapatti, Perumanayakam and the surrounding villages. Being roughly 45 km from our base, we schedule these as planned jobs rather than same-day walk-ins, but we still turn up on the day we say we will.",
                'localities' => ['Gobichettipalayam Town', 'Settur', 'Gudumani', 'Kongapatti', 'Perumanayakam', 'Kovilgiri Road', 'Bannari Road'],
                'popular_routes' => ['Gobichettipalayam to Erode', 'Gobichettipalayam to Coimbatore', 'Gobichettipalayam to Sathyamangalam', 'Gobichettipalayam to Bhavani'],
            ],
            [
                'name' => 'Anthiyur',
                'short_name' => 'Anthiyur',
                'state' => 'Tamil Nadu',
                'district' => 'Erode',
                'latitude' => 11.4161,
                'longitude' => 77.5792,
                'priority_tier' => 3,
                'sort_order' => 15,
                'excerpt' => 'Packers and movers in Anthiyur for local house shifting, packing, loading and transport across Erode district.',
                'meta_title' => 'Packers and Movers in Anthiyur | Local House Shifting Services',
                'meta_description' => 'Next Level Packers and Movers in Anthiyur — local house shifting, packing, loading and transport across Erode district. Call +91 93635 55311.',
                'description' => "Anthiyur is a small town between Bhavani and Erode, and for most jobs here we combine the pickup with a move elsewhere in the district rather than running a dedicated vehicle out and back.\n\nThat combination approach means Anthiyur customers get a local-move price rather than paying for a round trip nobody else was going to share. We handle house shifting, packing and loading here, plus the agricultural and small business transport that Anthiyur generates.",
                'localities' => ['Anthiyur Town', 'Kettur', 'Udumalai', 'Thaipattam', 'Veerappandi', 'Elathi'],
                'popular_routes' => ['Anthiyur to Erode', 'Anthiyur to Bhavani', 'Anthiyur to Sathyamangalam', 'Anthiyur to Coimbatore'],
            ],
            [
                'name' => 'Veppadai',
                'short_name' => 'Veppadai',
                'state' => 'Tamil Nadu',
                'district' => 'Erode',
                'latitude' => 11.3592,
                'longitude' => 77.7062,
                'priority_tier' => 3,
                'sort_order' => 16,
                'excerpt' => 'Packers and movers in Veppadai for house shifting, packing, loading and local transport in Erode district.',
                'meta_title' => 'Packers and Movers in Veppadai | House Shifting in Erode District',
                'meta_description' => 'Next Level Packers and Movers in Veppadai — house shifting, packing, loading and local transport in Erode district. Call +91 93635 55311.',
                'description' => "Veppadai is a small town on the Erode–Perundurai road, well inside our local radius.\n\nHouse shifting, packing and loading here are usually part of a wider district run, so we price them as local moves. We cover Veppadai town and the villages towards Perundurai and Modakkurichi, and we are happy to combine a Veppadai pickup with a delivery anywhere in Erode district.",
                'localities' => ['Veppadai Town', 'Periya Rakkasapalayam', 'Chettisamuthur', 'Kunnathur', 'Pudhur'],
                'popular_routes' => ['Veppadai to Erode', 'Veppadai to Perundurai', 'Veppadai to Coimbatore', 'Veppadai to Tiruppur'],
            ],
            [
                'name' => 'Chithode',
                'short_name' => 'Chithode',
                'state' => 'Tamil Nadu',
                'district' => 'Erode',
                'latitude' => 11.3436,
                'longitude' => 77.7195,
                'priority_tier' => 3,
                'sort_order' => 17,
                'excerpt' => 'Packers and movers in Chithode, Erode — our home base. House shifting, office moving, packing, loading and storage.',
                'meta_title' => 'Packers and Movers in Chithode, Erode | House Shifting & Storage',
                'meta_description' => 'Next Level Packers and Movers in Chithode, Erode — house shifting, office moving, packing, loading and storage. Call +91 93635 55311 for a free quote.',
                'description' => "Chithode on Sakthi Main Road is where our office and storage facility are located, at Nadapalayam. Most of our crews load and dispatch from here, which is why Chithode and the surrounding Erode neighbourhoods are the quickest bookings we can take.\n\nWe handle the full range here — house shifting, office relocation, packing, loading and unloading, and both short and long-term storage in our own godown. If you need to hold goods between a possession date and a move-in date, or between two business premises, this is the facility to ask about.",
                'localities' => ['Nadapalayam', 'Chithode', 'Sakthi Main Road', 'Aval Poondurai', 'Rangapalayam', 'Moolapalayam', 'Tindal', 'Vellakovil Road'],
                'popular_routes' => ['Chithode to Erode Town', 'Chithode to Coimbatore', 'Chithode to Tiruppur', 'Chithode to Perundurai'],
            ],
            [
                'name' => 'Chinnimalai',
                'short_name' => 'Chinnimalai',
                'state' => 'Tamil Nadu',
                'district' => 'Tiruppur',
                'latitude' => 11.1520,
                'longitude' => 77.6650,
                'priority_tier' => 3,
                'sort_order' => 18,
                'excerpt' => 'Packers and movers in Chinnimalai for house shifting, factory moving, packing, loading and transport.',
                'meta_title' => 'Packers and Movers in Chinnimalai | House Shifting & Factory Moving',
                'meta_description' => 'Next Level Packers and Movers in Chinnimalai — house shifting, factory and office moving, packing, loading and transport. Call +91 93635 55311.',
                'description' => "Chinnimalai sits between Erode and Tiruppur and has grown into a significant industrial and residential centre of its own, with a large textile and engineering presence.\n\nWe handle house shifting and packing across the town and the newer layouts, and the industrial side for units around the industrial estate including machinery, stock and complete factory setups. Since Chinnimalai sits on our Erode–Tiruppur run, we can usually combine a Chinnimalai movement with a job in either direction, which is good for the customer's cost.",
                'localities' => ['Chinnimalai Town', 'Industrial Estate', 'Kunnathur Road', 'Palladam Road', 'Smtp Colony', 'Kovilpatty', 'Vellaputhur'],
                'popular_routes' => ['Chinnimalai to Erode', 'Chinnimalai to Tiruppur', 'Chinnimalai to Coimbatore', 'Chinnimalai to Perundurai'],
            ],
            [
                'name' => 'Avinashi',
                'short_name' => 'Avinashi',
                'state' => 'Tamil Nadu',
                'district' => 'Tiruppur',
                'latitude' => 11.0430,
                'longitude' => 77.5080,
                'priority_tier' => 3,
                'sort_order' => 19,
                'excerpt' => 'Packers and movers in Avinashi for house shifting, office relocation, packing, loading and transport services.',
                'meta_title' => 'Packers and Movers in Avinashi | House Shifting & Office Relocation',
                'meta_description' => 'Next Level Packers and Movers in Avinashi — house shifting, office relocation, packing, loading and transport. Call +91 93635 55311 for a free quote.',
                'description' => "Avinashi is on the Erode–Tiruppur road and a natural stop on the Tiruppur runs, with a long industrial and residential history of its own.\n\nWe handle house shifting, packing and loading across Avinashi town and the surrounding villages, and industrial relocation for the units along the Avinashi road. Avinashi movements are typically scheduled alongside a Tiruppur job, so we can commit to a specific arrival time rather than a loose window.",
                'localities' => ['Avinashi Town', 'Industrial Area', 'Palayamkottai', 'Kuralayampalayam', 'Senbagaevalasur', 'Settipalayam'],
                'popular_routes' => ['Avinashi to Tiruppur', 'Avinashi to Erode', 'Avinashi to Coimbatore', 'Avinashi to Chinnimalai'],
            ],
            [
                'name' => 'Annur',
                'short_name' => 'Annur',
                'state' => 'Tamil Nadu',
                'district' => 'Coimbatore',
                'latitude' => 11.2350,
                'longitude' => 77.0530,
                'priority_tier' => 3,
                'sort_order' => 20,
                'excerpt' => 'Packers and movers in Annur for house shifting, packing, loading and local transport in Coimbatore district.',
                'meta_title' => 'Packers and Movers in Annur | House Shifting in Coimbatore District',
                'meta_description' => 'Next Level Packers and Movers in Annur — house shifting, packing, loading and local transport in Coimbatore district. Call +91 93635 55311.',
                'description' => "Annur lies on the Sathyamangalam route, north-east of Coimbatore, and is a common combined pickup for us on the way in or out of the city.\n\nWe handle house shifting, packing, loading and general transport across Annur and the surrounding villages. Annur jobs are usually priced as local moves within our Coimbatore working radius.",
                'localities' => ['Annur Town', 'Mangalam', 'Kovilpatti', 'Nallampalli', 'Thudur', 'Thirumalapuram'],
                'popular_routes' => ['Annur to Coimbatore', 'Annur to Sathyamangalam', 'Annur to Erode', 'Annur to Tiruppur'],
            ],
            [
                'name' => 'Pallipalayam',
                'short_name' => 'Pallipalayam',
                'state' => 'Tamil Nadu',
                'district' => 'Erode',
                'latitude' => 11.2806,
                'longitude' => 77.7136,
                'priority_tier' => 3,
                'sort_order' => 21,
                'excerpt' => 'Packers and movers in Pallipalayam for house shifting, packing, loading and local transport in Erode district.',
                'meta_title' => 'Packers and Movers in Pallipalayam | House Shifting & Packing',
                'meta_description' => 'Next Level Packers and Movers in Pallipalayam — house shifting, packing, loading and local transport in Erode district. Call +91 93635 55311.',
                'description' => "Pallipalayam is a small town between Erode and Perundurai, and one of the many Erode-district towns we cover on a local-move rate.\n\nHouse shifting, packing and loading here are combined with a wider district run wherever possible, which keeps the price down. We cover Pallipalayam town and the villages towards Perundurai and Unjalur.",
                'localities' => ['Pallipalayam Town', 'Unjalur', 'Kunnathur', 'Vellakovil', 'Perumanayakam'],
                'popular_routes' => ['Pallipalayam to Erode', 'Pallipalayam to Perundurai', 'Pallipalayam to Namakkal', 'Pallipalayam to Coimbatore'],
            ],
            [
                'name' => 'Tindal',
                'short_name' => 'Tindal',
                'state' => 'Tamil Nadu',
                'district' => 'Erode',
                'latitude' => 11.3430,
                'longitude' => 77.7370,
                'priority_tier' => 3,
                'sort_order' => 22,
                'excerpt' => 'Packers and movers in Tindal, Erode for local house shifting, packing, loading and same-day moving services.',
                'meta_title' => 'Packers and Movers in Tindal, Erode | Local House Shifting',
                'meta_description' => 'Next Level Packers and Movers in Tindal, Erode — local house shifting, packing, loading and same-day moving. Call +91 93635 55311 for a free quote.',
                'description' => "Tindal is a locality just off Erode Junction, only a few kilometres from our Chithode base, so moves here are same-day work and priced as local moves.\n\nWe handle house shifting, packing, loading and small goods transport across Tindal and the surrounding Erode neighbourhoods, often as part of a combined Erode-town run.",
                'localities' => ['Tindal', 'Erode Junction', 'Nadapalayam', 'Rangapalayam', 'Moolapalayam', 'Aval Poondurai'],
                'popular_routes' => ['Tindal to Erode Town', 'Tindal to Chithode', 'Tindal to Perundurai', 'Tindal to Coimbatore'],
            ],
            [
                'name' => 'Moolapalayam',
                'short_name' => 'Moolapalayam',
                'state' => 'Tamil Nadu',
                'district' => 'Erode',
                'latitude' => 11.3225,
                'longitude' => 77.7212,
                'priority_tier' => 3,
                'sort_order' => 23,
                'excerpt' => 'Packers and movers in Moolapalayam, Erode for local house shifting, packing, loading and same-day moving services.',
                'meta_title' => 'Packers and Movers in Moolapalayam, Erode | Local House Shifting',
                'meta_description' => 'Next Level Packers and Movers in Moolapalayam, Erode — local house shifting, packing, loading and same-day moving. Call +91 93635 55311.',
                'description' => "Moolapalayam is a residential locality a few kilometres from our Chithode base in Erode, so moves here are same-day and charged as local shifts.\n\nWe cover house shifting, packing, loading and small transport jobs across Moolapalayam and the adjacent Erode neighbourhoods. Being inside our home radius, we can usually turn up the same day if you call before 11 AM.",
                'localities' => ['Moolapalayam', 'Nadapalayam', 'Chithode', 'Rangapalayam', 'Sakthi Main Road'],
                'popular_routes' => ['Moolapalayam to Erode Town', 'Moolapalayam to Perundurai', 'Moolapalayam to Coimbatore', 'Moolapalayam to Tiruppur'],
            ],
            [
                'name' => 'Rangapalayam',
                'short_name' => 'Rangapalayam',
                'state' => 'Tamil Nadu',
                'district' => 'Erode',
                'latitude' => 11.3270,
                'longitude' => 77.7070,
                'priority_tier' => 3,
                'sort_order' => 24,
                'excerpt' => 'Packers and movers in Rangapalayam, Erode for local house shifting, packing, loading and same-day moving services.',
                'meta_title' => 'Packers and Movers in Rangapalayam, Erode | Local House Shifting',
                'meta_description' => 'Next Level Packers and Movers in Rangapalayam, Erode — local house shifting, packing, loading and same-day moving. Call +91 93635 55311.',
                'description' => "Rangapalayam is a residential locality on the Erode periphery, well within our same-day range from the Chithode base.\n\nHouse shifting, packing and loading here are handled as local moves, usually combined with a run elsewhere in Erode. We cover Rangapalayam and the neighbouring Erode layouts including Moolapalayam and Nadapalayam.",
                'localities' => ['Rangapalayam', 'Moolapalayam', 'Nadapalayam', 'Chithode', 'Perundurai Road'],
                'popular_routes' => ['Rangapalayam to Erode Town', 'Rangapalayam to Perundurai', 'Rangapalayam to Coimbatore', 'Rangapalayam to Tiruppur'],
            ],
            [
                'name' => 'Aval Poondurai',
                'short_name' => 'Aval Poondurai',
                'state' => 'Tamil Nadu',
                'district' => 'Erode',
                'latitude' => 11.3458,
                'longitude' => 77.7420,
                'priority_tier' => 3,
                'sort_order' => 25,
                'excerpt' => 'Packers and movers in Aval Poondurai, Erode for local house shifting, packing, loading and same-day moving services.',
                'meta_title' => 'Packers and Movers in Aval Poondurai, Erode | Local House Shifting',
                'meta_description' => 'Next Level Packers and Movers in Aval Poondurai, Erode — local house shifting, packing, loading and same-day moving. Call +91 93635 55311.',
                'description' => "Aval Poondurai is a locality immediately around our Chithode facility in Erode, so moves here are same-day and priced as local shifts.\n\nWe handle house shifting, packing, loading and small transport jobs across Aval Poondurai, Tindal and the neighbouring Erode areas, and we also run our storage facility from this immediate area for customers who need holding space between a possession and a move-in.",
                'localities' => ['Aval Poondurai', 'Chithode', 'Nadapalayam', 'Tindal', 'Sakthi Main Road'],
                'popular_routes' => ['Aval Poondurai to Erode Town', 'Aval Poondurai to Perundurai', 'Aval Poondurai to Coimbatore', 'Aval Poondurai to Tiruppur'],
            ],
        ];

        foreach ($locations as $location) {
            $name = $location['name'];
            unset($location['name']);

            Location::updateOrCreate(
                ['slug' => Str::slug($name)],
                array_merge($location, [
                    'name' => $name,
                    'icon' => 'ph:map-pin-fill',
                    'is_active' => true,
                ]),
            );
        }
    }
}
